name: lingochat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  flex_color_scheme: ^8.0.1
  firebase_storage: ^12.3.6
  firebase_database: ^11.1.6
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  image_picker: ^1.1.2
  backdrop: ^0.9.1
  flutter_svg: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/img/logo.png

  fonts:
    - family: Rubik-Regular
      fonts:
        - asset: lib/assets/fonts/Rubik-Regular.ttf